# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "cataclysm:coral_golem",
    "clay:soldier/cyan",
    "alexsmobs:snow_leopard",
    "clay:horse/gravel",
    "born_in_chaos_v1:siamese_skeletonsleft",
    "born_in_chaos_v1:siamese_skeletonsright",
    "clay:horse/grass",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "born_in_chaos_v1:lifestealer",
    "piglet_structures:wheatbug",
    "minecraft:llama",
    "alexscaves:underzealot",
    "clay:horse/mycelium",
    "alexsmobs:skreecher",
    "cataclysm:ender_guardian",
    "cataclysm:deepling_warlock",
    "zoe:biostation",
    "minecraft:tadpole",
    "alexscaves:corrodent",
    "rats:ratlantean_ratbot",
    "piglet_structures:chair_seat",
    "alexsmobs:hammerhead_shark",
    "alexscaves:magnetron",
    "jigsaw_pp:zombie_beaver_spawner",
    "alexsmobs:grizzly_bear",
    "alexsmobs:murmur_head",
    "zoe:fyber",
    "piglet_structures:garden_guardian",
    "minecraft:mooshroom",
    "born_in_chaos_v1:seared_spirit_not_despawn",
    "minecraft:axolotl",
    "botania:doppleganger",
    "clay:soldier/brown",
    "alexsmobs:gorilla",
    "jigsaw_pp:beaver_spider",
    "alexsmobs:cosmic_cod",
    "piglet_structures:blaze_spark",
    "piglet_structures:skeleton_fly",
    "rats:ratlantean_automaton",
    "alexscaves:deep_one_mage",
    "alexsmobs:kangaroo",
    "piglet_structures:stormy_slime",
    "born_in_chaos_v1:corpse_fish",
    "born_in_chaos_v1:supreme_bonescaller_stage_2",
    "rats:plague_beast",
    "piglet_structures:the_laser",
    "alexsmobs:hummingbird",
    "mutantmonsters:mutant_zombie",
    "piglet_structures:warper",
    "zoe:empress_of_lightning",
    "alexscaves:deep_one",
    "jigsaw_pp:teapod_spider",
    "alexsmobs:crow",
    "trapcraft:dummy",
    "alexsmobs:guster",
    "born_in_chaos_v1:bone_imp",
    "piglet_structures:flamey",
    "born_in_chaos_v1:nightmare_stalker",
    "piglet_structures:flying_book",
    "cataclysm:koboleton",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "alexsmobs:emu",
    "born_in_chaos_v1:siamese_skeletons",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "born_in_chaos_v1:lords_felsteed",
    "clay:horse/soul_sand",
    "minecraft:zombified_piglin",
    "minecraft:sheep",
    "piglet_structures:the_garden_gnome",
    "born_in_chaos_v1:lord_pumpkinhead_withouta_horse",
    "alexsmobs:bone_serpent_part",
    "alexsmobs:raccoon",
    "born_in_chaos_v1:fallen_chaos_knight",
    "minecraft:ravager",
    "alexsmobs:bone_serpent",
    "clay:soldier/red",
    "piglet_structures:spooker",
    "born_in_chaos_v1:riding_lords_felsteed",
    "alexsmobs:mudskipper",
    "alexsmobs:crimson_mosquito",
    "clay:horse/grassy",
    "arthropocolypse:wharf_roach",
    "alexsmobs:jerboa",
    "piglet_structures:the_redstone",
    "born_in_chaos_v1:bloody_gadfly",
    "piglet_structures:fake_garden_gnome",
    "alexsmobs:comb_jelly",
    "born_in_chaos_v1:skeleton_thrasher",
    "railways:conductor",
    "born_in_chaos_v1:controlled_spiritual_assistant",
    "rats:demon_rat",
    "piglet_structures:driller",
    "alexsmobs:enderiophage",
    "alexsmobs:sunbird",
    "minecraft:cat",
    "minecraft:tropical_fish",
    "cataclysm:the_prowler",
    "alexscaves:gloomoth",
    "alexscaves:vesper",
    "zoe:betrayal",
    "alexscaves:lanternfish",
    "minecraft:zombie_villager",
    "clay:horse/lapis",
    "born_in_chaos_v1:dire_hound_leader",
    "alexsmobs:froststalker",
    "minecraft:giant",
    "alexsmobs:lobster",
    "mowziesmobs:lantern",
    "alexsmobs:seagull",
    "alexscaves:brainiac",
    "rats:ratfish",
    "jigsaw_pp:zombie_beaver",
    "clay:horse/sand",
    "arthropocolypse:platerodrilus",
    "minecraft:husk",
    "piglet_structures:kwik_salesman_plains",
    "born_in_chaos_v1:firelight_not_despawn",
    "piglet_structures:jumpy_ball",
    "born_in_chaos_v1:door_knight",
    "mowziesmobs:umvuthana",
    "alexscaves:luxtructosaurus",
    "minecraft:donkey",
    "rats:plague_cloud",
    "mowziesmobs:umvuthana_crane_player",
    "mutantmonsters:mutant_skeleton",
    "cataclysm:the_leviathan",
    "minecraft:piglin_brute",
    "cataclysm:the_baby_leviathan",
    "cataclysm:deepling_brute",
    "arthropocolypse:ice_crawler",
    "alexsmobs:frilled_shark",
    "born_in_chaos_v1:pumpkin_spirit",
    "piglet_structures:the_suspicious_garden_gnome",
    "alexsmobs:bald_eagle",
    "clay:soldier/magenta",
    "alexsmobs:blobfish",
    "born_in_chaos_v1:infernal_spirit",
    "alexsmobs:void_worm",
    "born_in_chaos_v1:sir_pumpkinhead_without_horse",
    "minecraft:parrot",
    "alexsmobs:centipede_head",
    "cataclysm:the_watcher",
    "piglet_structures:charging_garden_gnome",
    "alexsmobs:banana_slug",
    "mutantmonsters:mutant_creeper",
    "clay:soldier/purple",
    "alexsmobs:bunfungus",
    "minecraft:mule",
    "minecraft:vindicator",
    "alexsmobs:flying_fish",
    "zoe:anthropophobia",
    "piglet_structures:kwik_salesman_ocean",
    "cataclysm:nameless_sorcerer",
    "cataclysm:endermaptera",
    "pneumaticcraft:guard_drone",
    "cataclysm:lionfish",
    "piglet_structures:mineral_scorpio",
    "born_in_chaos_v1:corpse_fly",
    "cataclysm:coralssus",
    "piglet_structures:lumberer",
    "cataclysm:the_harbinger",
    "alexsmobs:terrapin",
    "clay:horse/snow",
    "arthropocolypse:behemoth_desert_spider",
    "minecraft:pig",
    "born_in_chaos_v1:restless_spirit",
    "alexsmobs:alligator_snapping_turtle",
    "minecraft:cod",
    "arthropocolypse:behemoth_desert_scorpion",
    "alexsmobs:platypus",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "born_in_chaos_v1:scarlet_persecutor",
    "born_in_chaos_v1:phantom_creeper_copy",
    "alexsmobs:soul_vulture",
    "alexsmobs:blue_jay",
    "piglet_structures:the_freezer",
    "minecraft:salmon",
    "cataclysm:ignis",
    "mowziesmobs:naga",
    "born_in_chaos_v1:seared_spirit",
    "alexsmobs:anteater",
    "alexsmobs:rain_frog",
    "mowziesmobs:ferrous_wroughtnaut",
    "born_in_chaos_v1:zombie_clown",
    "minecraft:rabbit",
    "minecraft:pillager",
    "born_in_chaos_v1:decaying_zombie_not_despawn",
    "minecraft:zoglin",
    "born_in_chaos_v1:zombie_bruiser",
    "alexsmobs:leafcutter_ant",
    "thermal:basalz",
    "born_in_chaos_v1:lord_the_headless",
    "born_in_chaos_v1:diamond_termite",
    "jigsaw_pp:stone_beaver",
    "arthropocolypse:stag_beetle",
    "cataclysm:deepling_priest",
    "arthropocolypse:millipede_head",
    "piglet_structures:armored_garden_gnome",
    "rats:feral_ratlantean",
    "cataclysm:ignited_revenant",
    "clay:horse/cake",
    "alexsmobs:gazelle",
    "minecraft:sniffer",
    "zoe:cyborg",
    "piglet_structures:chocolate_cow",
    "alexscaves:watcher",
    "born_in_chaos_v1:missioner",
    "arthropocolypse:field_cricket",
    "mowziesmobs:umvuthana_follower_player",
    "cataclysm:modern_remnant",
    "born_in_chaos_v1:supreme_bonescaller_not_despawn",
    "alexsmobs:seal",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "clay:horse/clay",
    "born_in_chaos_v1:riding_felsteed",
    "born_in_chaos_v1:pumpkin_bomb",
    "alexsmobs:maned_wolf",
    "born_in_chaos_v1:skeleton_demoman",
    "minecraft:dolphin",
    "neapolitan:plantain_spider",
    "born_in_chaos_v1:supreme_bonescaller",
    "alexsmobs:gelada_monkey",
    "arthropocolypse:worker_ant",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "arthropocolypse:mealworm",
    "minecraft:bee",
    "alexsmobs:devils_hole_pupfish",
    "pneumaticcraft:harvesting_drone",
    "minecraft:illusioner",
    "piglet_structures:the_redstone_small",
    "born_in_chaos_v1:dread_hound",
    "born_in_chaos_v1:skeleton_thrasher_not_despawn",
    "alexsmobs:bison",
    "rats:plague_doctor",
    "mowziesmobs:foliaath",
    "pneumaticcraft:amadrone",
    "mowziesmobs:frostmaw",
    "minecraft:drowned",
    "arthropocolypse:soldier_ant",
    "rats:ghost_pirat",
    "born_in_chaos_v1:bone_imp_minion",
    "alexsmobs:tusklin",
    "born_in_chaos_v1:senor_pumpkin",
    "alexsmobs:underminer",
    "minecraft:wandering_trader",
    "zoe:atrophy",
    "born_in_chaos_v1:glutton_fish",
    "clay:soldier/lime",
    "cataclysm:netherite_monstrosity",
    "create_sa:brass_drone",
    "rats:pied_piper",
    "cataclysm:wadjet",
    "alexscaves:boundroid",
    "mowziesmobs:umvuthana_raptor",
    "jigsaw_pp:blabbit",
    "minecraft:pufferfish",
    "minecraft:fox",
    "born_in_chaos_v1:firelight",
    "mowziesmobs:umvuthana_crane",
    "alexsmobs:warped_toad",
    "born_in_chaos_v1:mr_pumpkin_controlled",
    "piglet_structures:the_bricker",
    "alexsmobs:cockroach",
    "born_in_chaos_v1:lord_pumpkinhead",
    "born_in_chaos_v1:zombie_lumberjack",
    "neapolitan:chimpanzee",
    "rats:neo_ratlantean",
    "alexscaves:ferrouslime",
    "cataclysm:deepling_angler",
    "alexsmobs:capuchin_monkey",
    "minecraft:polar_bear",
    "piglet_structures:little_spike",
    "clay:horse/snowy",
    "minecraft:turtle",
    "born_in_chaos_v1:lord_pumpkinhead_head",
    "alexsmobs:rattlesnake",
    "piglet_structures:screecher",
    "born_in_chaos_v1:zombie_fisherman",
    "born_in_chaos_v1:controlled_baby_skeleton",
    "arthropocolypse:prairie_grasshopper",
    "clay:soldier/blue",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "alexscaves:trilocaris",
    "alexsmobs:straddler",
    "born_in_chaos_v1:door_knight_not_despawn",
    "alexsmobs:sea_bear",
    "born_in_chaos_v1:spirit_guide",
    "rats:rat_baron_plane",
    "born_in_chaos_v1:dread_hound_not_despawn",
    "alexscaves:nucleeper",
    "alexscaves:hullbreaker",
    "born_in_chaos_v1:zombie_clown_not_despawn",
    "mowziesmobs:umvuthana_follower_raptor",
    "cataclysm:ender_golem",
    "alexsmobs:sugar_glider",
    "supplementaries:red_merchant",
    "pneumaticcraft:programmable_controller",
    "alexsmobs:orca",
    "born_in_chaos_v1:spiritof_chaos",
    "born_in_chaos_v1:sir_pumpkinhead",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "piglet_structures:flamey_spark",
    "piglet_structures:scrappy",
    "born_in_chaos_v1:decrepit_skeleton",
    "zoe:introvercy",
    "arthropocolypse:stag_beetle_larva",
    "born_in_chaos_v1:bonescaller_not_despawn",
    "alexsmobs:skunk",
    "born_in_chaos_v1:baby_skeleton",
    "rats:pirat_boat",
    "born_in_chaos_v1:lifestealer_true_form",
    "rats:rat_king",
    "cataclysm:deepling",
    "alexsmobs:tasmanian_devil",
    "born_in_chaos_v1:thornshell_crab",
    "cataclysm:ancient_remnant",
    "alexsmobs:stradpole",
    "minecraft:panda",
    "ghastcow:ghast_cow",
    "alexsmobs:moose",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "cataclysm:amethyst_crab",
    "born_in_chaos_v1:maggot",
    "rats:rat_baron",
    "alexsmobs:warped_mosco",
    "clay:soldier/orange",
    "clay:horse/carrot",
    "rats:ratlantean_spirit",
    "piglet_structures:charging_garden_gnome_summon",
    "alexsmobs:komodo_dragon",
    "piglet_structures:axe_stray",
    "born_in_chaos_v1:felsteed",
    "alexscaves:forsaken",
    "born_in_chaos_v1:spirit_guide_assistant",
    "alexscaves:mine_guardian",
    "born_in_chaos_v1:baby_skeleton_minion",
    "clay:soldier/pink",
    "clay:soldier/black",
    "cataclysm:ignited_berserker",
    "alexsmobs:crocodile",
    "alexscaves:teletor",
    "jigsaw_pp:moss_elephant",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "born_in_chaos_v1:mr_pumpkin",
    "alexsmobs:mimicube",
    "born_in_chaos_v1:phantom_creeper",
    "thermal:blizz",
    "vinery:mule",
    "minecraft:frog",
    "piglet_structures:ancient_skeleton_warrior",
    "clay:soldier/lightblue",
    "alexsmobs:mimic_octopus",
    "clay:soldier/white",
    "alexsmobs:void_worm_part",
    "pneumaticcraft:collector_drone",
    "vinery:wandering_winemaker",
    "minecraft:evoker",
    "born_in_chaos_v1:barrel_zombie",
    "alexsmobs:tarantula_hawk",
    "alexsmobs:cachalot_whale",
    "rats:black_death",
    "zoe:cycrawler",
    "born_in_chaos_v1:decaying_zombie",
    "piglet_structures:compost_fairy",
    "alexscaves:gammaroach",
    "clay:soldier/green",
    "rats:dutchrat",
    "alexscaves:notor",
    "clay:horse/dirt",
    "alexsmobs:anaconda",
    "born_in_chaos_v1:phantom_bomb_entity",
    "thermal:blitz",
    "mowziesmobs:grottol",
    "mowziesmobs:baby_foliaath",
    "born_in_chaos_v1:swarmer",
    "minecraft:goat",
    "mutantmonsters:mutant_enderman",
    "alexsmobs:mantis_shrimp",
    "clay:soldier/gray",
    "clay:soldier/clay",
    "born_in_chaos_v1:pumpkinhead",
    "mutantmonsters:spider_pig",
    "mowziesmobs:umvuthi",
    "create_dd:seething_ablaze",
    "alexscaves:radgill",
    "alexsmobs:toucan",
    "rats:pirat",
    "born_in_chaos_v1:dark_vortex",
    "alexsmobs:murmur",
    "pneumaticcraft:drone",
    "alexsmobs:mungus",
    "alexsmobs:caiman",
    "pneumaticcraft:logistics_drone",
    "alexsmobs:spectre",
    "cataclysm:kobolediator",
    "alexsmobs:catfish",
    "piglet_structures:pillager_scientist",
    "arthropocolypse:scarab",
    "mutantmonsters:endersoul_clone",
    "minecraft:piglin",
    "alexsmobs:skelewag",
    "create_dd:inert_blazeling",
    "born_in_chaos_v1:sir_the_headless",
    "alexscaves:boundroid_winch",
    "alexscaves:deep_one_knight",
    "alexsmobs:elephant",
    "clay:soldier/yellow",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "born_in_chaos_v1:bonescaller",
    "piglet_structures:armored_garden_gnome_summon",
    "piglet_structures:mummy",
    "piglet_structures:perceiver",
    "minecraft:ocelot",
    "minecraft:wolf",
    "arthropocolypse:mealworm_beetle"
]
